- name: create ec2 and update route 53
  hosts: localhost
  connection: local
  #become: yes
  vars:
    AMI_ID: "ami-0220d79f3f480ecf5"
    SG_ID: "sg-0cec9364e954bfbdd"
    INSTANCE_TYPE: "t3.micro"
    DOMAIN: "prudhvii.fun"
    ZONE_ID: "Z00068622FEPCRKDV786J"
    # instances:
    # - catalogue
    # - redis
    # - rabbitmq
    # - mongodb
    # - mysql

  tasks:
  - name: create aws ec2
    amazon.aws.ec2_instance:
      state: present
      name: "{{ item }}"
      instance_type: "{{ INSTANCE_TYPE }}"
      security_group: "{{ SG_ID }}"
      image_id: "{{ AMI_ID }}"
      tags:
        Environment: test
    loop: "{{ instances }}"
    register: ec2_output

  # - name: print the ec2_output
  #   ansible.builtin.debug:
  #     msg: "{{ ec2_output }}"

  # - name: print public_ip
  #   ansible.builtin.debug: 
  #     msg: "{{ item.instances[0].public_ip_address }}"
  #   loop: "{{ ec2_output.results }}"

  # - name: print private_ip
  #   ansible.builtin.debug: 
  #     msg: "{{ item.instances[0].private_ip_address }}"
  #   loop: "{{ ec2_output.results }}"

  - name: create route53 record
    amazon.aws.route53:
      state: present
      zone: "{{ DOMAIN }}"
      record: "{{ item.item }}.{{ DOMAIN }}" # mongodb.daws86s.fun
      type: A
      ttl: 1
      value: "{{ item.instances[0].private_ip_address }}"
      overwrite: true
    loop: "{{ ec2_output.results }}"

  # we are creating one record with public only for frontend
  - name: create route53 record for frontend
    amazon.aws.route53:
      state: present
      zone: "{{ DOMAIN }}"
      record: "{{ DOMAIN }}" # daws86s.fun
      type: A
      ttl: 1
      value: "{{ item.instances[0].public_ip_address }}"
      overwrite: true
    when: item.item == "frontend"
    loop: "{{ ec2_output.results }}"